In [1]:
# import

import pandas as pd
from dataclasses import dataclass, asdict
from PIL import Image, ImageChops, ImageDraw, ImageFont
from pprint import pprint
import numpy as np
import random
import os

In [12]:
# test load quick draw
apple = np.load('../data/sketch_rnn/apple.npz', encoding='latin1', allow_pickle=True)
print(apple.files)
print(apple['train'][0].shape)
print(apple['train'][0])

['test', 'train', 'valid']
(43, 3)
[[-17 -18   0]
 [-19 -14   0]
 [-32  -2   0]
 [-13   5   0]
 [-17  11   0]
 [ -9  11   0]
 [ -9  48   0]
 [  3  32   0]
 [  9  15   0]
 [ 64  70   0]
 [  9  45   0]
 [ 10  10   0]
 [ 19   3   0]
 [ 12 -15   0]
 [ 22   0   0]
 [ 10   6   0]
 [  5  -2   0]
 [ 15 -34   0]
 [ 37 -37   0]
 [  5 -10   0]
 [  6 -15   0]
 [  6 -33   0]
 [  2 -37   0]
 [ -5 -13   0]
 [-12 -15   0]
 [-48 -33   0]
 [-13  -1   0]
 [-14   6   0]
 [-18  15   0]
 [ -5   8   1]
 [  3 -19   0]
 [ -1 -16   0]
 [ 27 -54   1]
 [-18  28   0]
 [  4  -5   0]
 [ 30  -9   0]
 [ 19  -1   0]
 [ 31  18   0]
 [ -8   0   0]
 [-19   7   0]
 [-25  16   0]
 [-22   1   0]
 [-18  -8   1]]
